logo: '/images/milo.png'
topNav:
  globalLinks:
    display: true
    links:
    - title: 'Home'
      url: '/'
    - title: 'Get Started'
      url: '/get-started/'
  dropdown:
    display: true
    name: "Dropdown"
    url: "/"             
    links:              
      - name: "About Us"
        url: "/about"
      - name: "Services"
        url: "/services"
      - name: "Contact"
        url: "/contact"
names:
  organization: 'Emdash'
  product: 'MiloDocs'
version: 
  major: 0
  minor: 0
  patch: 3
article:
  childArticles:
    display: true
    count: 7 
    titleTrunc: 90
    descTrunc: 90
  nextPrev: 
    display: true
    trunc: 35
  chat: 
    display: true
  toc: 
    display: true
